name: CI-CD for Release Canidate
on: 
  push:
    branches:
      - release/**
      - hotfix/**
      
jobs:
  create_STG_PR:
    name: Create or update release PR for STG
    uses: ./.github/workflows/release.yml
    with:
      target_env: int
      
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Validate release date
        run: |
          echo "RELEASE_BRANCH_NAME=${{ github.ref_name }}"
