name: CI-CD for Release Canidate
on: 
 workflow_call:
    inputs:      
      commitHash:
        type: string
        required: false
 push:
   branches:
     - release/**
     - hotfix/**
      
jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Validate release date
        run: |
          echo "RELEASE_BRANCH_NAME=${{ github.ref_name }}"
