name: CI-CD for Release Canidate
on: 
 workflow_call:
    inputs:      
      commitHash:
        type: string
        required: false
 push:
   branches:
     - release/**
     - hotfix/**
      
jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
          
      - name: Validate release date
        run: |
          echo "RELEASE_BRANCH_NAME=$(git branch --show-current)"
