name: CI-CD for Release Canidate
on: 
  push:
    branches:
      - release/**
      - hotfix/**
      
jobs:
  build_test:
    if: (startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/')) && (inputs.target_env == 'STG' || inputs.target_env == 'PRD')
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Validate release date
        run: |
          echo "RELEASE_BRANCH_NAME=${{ github.ref_name }}"
