# This workflows allows for a manually triggered update of the encrypted secrets in application config

name: Encrypt Secrets

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Log level'     
        required: true
        default: 'INT'
      commit_message:
        description: 'Message to use for secrets commit'  

jobs:
  encrypt_secrets:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      
      - name: Add Nuget sources
        run: dotnet nuget add source https://www.myget.org/F/aspnetwebstacknightly/ -n pf.org
        
      - name: Install PF cli
        run: dotnet tool install -g dotnetsay 
        
      - name: Assume correct Upper IAM role
        run: echo "aws sts assume-role --role-arn 'arn:aws:iam::248362051620:role/UpperBuildAgent'"
        
      # Execute the pf cli
      - name: Run the tool
        run: |
          cd Controllers
          dotnetsay ${{ github.event.inputs.environment }} > appsettings.INT.json
     
     # Create branch and PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "${{ github.event.inputs.commit_message }}"
          title: "Update secrets for ${{ github.events.inputs.environment }}"
          body: Encrypting secret values from AWS Secret Manager.
          branch: "update-${{ github.events.inputs.environment }}-secrets"
