name: Start Release Manual Workflow
on:
  workflow_dispatch:
    inputs:
      releaseDate:
        description: 'Date of release'
        required: true
        type: string
        
      commitHash:
        description: 'Specific Commit Hash (Optional)'
        required: false
        type: string

jobs:
  start_release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate release date
        run: |
          echo "RELEASE_DATE=$(date -d "${{inputs.releaseDate}}")" >> $GITHUB_ENV

      - name: Creating release branch
        run: echo "releasedate=$RELEASE_DATE"
