name: Start Release Manual Workflow
on:
  workflow_dispatch:
    inputs:
      releaseDate:
        description: 'Date of release'
        required: true
        type: string
        
      commitHash:
        description: 'Specific Commit Hash (Optional)'
        required: false
        type: string

jobs:
  start_release:
    runs-on: ubuntu-latest
    environment: RC
    steps:
      - name: Validate release date
        run: |
          releaseDate=$(date -I -d "${{ inputs.releaseDate }}") 
          echo "RELEASE_BRANCH_NAME=${releaseDate}_EHR" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
        
      - name: Creating release branch
        run: |
          echo "Release Branch Name:$RELEASE_BRANCH_NAME"
          git checkout -b release/$RELEASE_BRANCH_NAME
          git push --set-upstream origin release/$RELEASE_BRANCH_NAME
