name: Start Release Manual Workflow
on:
  workflow_dispatch:
    inputs:
      releaseDate:
        description: 'Date of release'
        required: true
        type: string
        
      commitHash:
        description: 'Specific Commit Hash (Optional)'
        required: false
        type: string

jobs:
  start_release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate release date
        run: |
          releaseDate=$(date -d "${{ inputs.releaseDate }}" -I 2>/dev/null)
          if [ ! $releaseDate ]
          then
              echo "::error Must supply a valid date for the release. '${{ inputs.releaseDate }}'"
              exit 1
          fi
          echo "RELEASE_BRANCH_NAME=${releaseDate}_EHR" >> $GITHUB_ENV

      - name: Creating release branch
        run: echo "releasedate=$RELEASE_BRANCH_NAME"
