name: Start Release Manual Workflow
on:
  workflow_dispatch:
    inputs:
      releaseDate:
        description: 'Date of release'
        required: true
        type: string
        
      commitHash:
        description: 'Specific Commit Hash (Optional)'
        required: false
        type: string

jobs:
  start_release:
    runs-on: ubuntu-latest
    outputs:
      release_branch_name: ${{ steps.validate.outputs.release_branch_name }}
    steps:
      - name: Validate release date
        id: validate
        run: |
          releaseDate=$(date -I -d "${{ inputs.releaseDate }}") 
          echo "RELEASE_BRANCH_NAME=${releaseDate}_EHR" >> $GITHUB_ENV
          echo "release_branch_name=${releaseDate}_EHR" >> $GITHUB_OUTPUT
          
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
          
      - name: Release Summary
        run: |
          commitInfo="$(git log -1 --format=oneline)" 
          echo "Starting a release for $RELEASE_BRANCH_NAME from" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- $commitInfo " >> $GITHUB_STEP_SUMMARY
      
       
  create_release_branch:
    needs: start_release
    runs-on: ubuntu-latest
    environment: RC
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commitHash }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Creating release branch
        run: |
          git checkout -b release/${{ needs.start_release.outputs.release_branch_name }}
          git push --set-upstream origin release/${{ needs.start_release.outputs.release_branch_name }}
  
